name: flutter_mcp_client
description: Flutter implementation of Model Context Protocol (MCP) client for connecting to MCP servers
version: 0.0.1
homepage: https://github.com/app-appplayer/flutter_mcp_client

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  mcp_client: ^0.1.1
  flutter_mcp_common: ^0.0.1
  #  path: ../flutter_mcp_common
  provider: ^6.0.5
  rxdart: ^0.27.7
  equatable: ^2.0.5
  uuid: ^4.0.0
  logger: ^2.0.1
  shared_preferences: ^2.5.2
  connectivity_plus: ^4.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.2
  build_runner: ^2.4.6
  plugin_platform_interface: ^2.1.6

flutter:
  plugin:
    platforms:
      android:
        package: com.appplayer.flutter_mcp_client
        pluginClass: FlutterMcpClientPlugin
      ios:
        pluginClass: FlutterMcpClientPlugin
      web:
        pluginClass: FlutterMcpClientWeb
        fileName: flutter_mcp_client_web.dart
      macos:
        pluginClass: FlutterMcpClientPlugin
      windows:
        pluginClass: FlutterMcpClientPluginCApi
      linux:
        pluginClass: FlutterMcpClientPlugin